name: lecture_alarm_20_1
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  provider: ^4.0.0
  firebase_messaging: ^6.0.0
  toast: ^0.1.5
  flutter_ringtone_player: ^1.0.3
  shared_preferences: ^0.5.6
  firebase_admob: ^0.9.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
